apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: wandb
spec:
  scaleTargetRef:
    name: wandb
  minReplicaCount: 1
  maxReplicaCount: 20
  pollingInterval: 1
  triggers:
    - type: external-push
      metadata:
        scalerAddress: 34.131.108.141:80
        governer: unschedulable-pod
        namespace: default
