apiVersion: apps/v1
kind: Deployment
metadata:
  name: global-pod-autoscaler
  labels:
    app: global-pod-autoscaler
spec:
  selector:
    matchLabels:
      app: global-pod-autoscaler
  template:
    metadata:
      labels:
        app: global-pod-autoscaler
    spec:
      terminationGracePeriodSeconds: 6
      serviceAccountName: global-pod-autoscaler
      containers:
        - name: global-pod-autoscaler
          image: aesher9o1/global-pod-autoscaler:0.0.1
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 200m
              memory: 300M
            limits:
              cpu: 300m
              memory: 1G
---
apiVersion: v1
kind: Service
metadata:
  name: global-pod-autoscaler
spec:
  type: LoadBalancer
  selector:
    app: global-pod-autoscaler
  ports:
    - port: 80
      targetPort: 3000
