apiVersion: v1
kind: ServiceAccount
metadata:
  name: global-pod-autoscaler
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-replica-viewer
  namespace: default
rules:
  - apiGroups: ['apps']
    resources: ['deployments', 'replicasets']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['autoscaling']
    resources: ['horizontalpodautoscalers']
    verbs: ['get', 'list', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-replica-viewer-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: global-pod-autoscaler # replace with name of your service account
    namespace: default
roleRef:
  kind: ClusterRole
  name: pod-replica-viewer
  apiGroup: rbac.authorization.k8s.io
